### ISSUE TITLE
サイト全体のデザインをどうするか決める

### ISSUE THREAD

**Issue by ndxbn** [sana-nantori-1st-anniversary/sana-nantori-1st-anniversary.github.io#1]
例えば https://mito1st.sanjiyoji.net/index.html は、古き良きテキストサイト時代のページみたいにしてるわけで。

**Comment by naporin0624** [comment]
ホーム画面をいつもの名取の配信している病室的なデザインにして、クッソ分厚いドアをクリックしていろんなコンテンツに飛んでいくって言う感じはどう？(この案がデザインかどうかって話だけど)

**Comment by ndxbn** [comment]
ニコニコ動画 (RC) のころのトップ画面のパロディみたいにしたいなーっていうのもある

バーチャルサナトリウムを徘徊（？）する感じのサイトデザインも良い（なぽせんせえが言ってるやつ）

土曜日に着手するまでには決めるー
