### ISSUE TITLE
公開日決める

### ISSUE THREAD

**Issue by ndxbn** [sana-nantori-1st-anniversary/sana-nantori-1st-anniversary.github.io#3]
候補は、「2/28（最初のツイート）」「3/7（誕生日）」「3/16（最初の動画投稿）」。

28日でいいかなって思ってるのだけれど。

**Comment by naporin0624** [comment]
全体的に間に合いそうなら2/28で全然大丈夫だと思われる・・・・

3/7に合わせてもいいかなって思うけど

**Comment by ndxbn** [comment]
3月7日公開にしますね
