### ISSUE TITLE
にっけさんと苺ざるそばさんが重なっている

### ISSUE THREAD

**Issue by forno** [sana-nantori-1st-anniversary/sana-nantori-1st-anniversary.github.io#8]
おそらく把握済みとは存じますが，PCから見たときににっけさんと苺ざるそばさんが重なっています．

テスト環境:

| Name | Value |
| - | - |
| OS | Windows 10 |
| Display | 1920x1080 |
| Browser | Chrome |

見たところ，にっけさんの表示位置がずれているように思います．
にっけさんの名前のテキストリンクが表示されておらず，gridをはみ出して表示されていると思います．

![image](https://user-images.githubusercontent.com/11057257/54148345-62bf1e00-4477-11e9-9121-bd1f94f0ca5b.png)

また，Chromeのスマホモードで確認したところ苺ざるそばさんが完全に視認できなくなっています．

![image](https://user-images.githubusercontent.com/11057257/54148897-67d09d00-4478-11e9-9afe-4c8ff474c94d.png)

ご報告まで．

**Comment by ndxbn** [comment]
ごめんなさい、気づいていました。ツイートについてるメディアをどのように見せるかを考え中で、直してない状態です。

ツイートに添付されているメディアだけを表示し、クリックしたらもとのツイートに飛ぶリンクをつけようかなって思ってます。木金あたりで直す予定です。
